global_set(CMAKE_C_COMPILER "${__CMAKE_C_COMPILER}")
global_set(CMAKE_CXX_COMPILER "${__CMAKE_CXX_COMPILER}")
global_set(CMAKE_LINKER "${__CMAKE_LINKER}")
global_set(CMAKE_AR "${__CMAKE_AR}")
global_set(CMAKE_OBJCOPY "${__CMAKE_OBJCOPY}")
global_set(CMAKE_SIZE "${__CMAKE_SIZE}")
global_set(CMAKE_OBJDUMP "${__CMAKE_OBJDUMP}")
